### ISSUE TITLE
Wiki How Build Works need small update

### ISSUE THREAD

**Issue by patlachance** [accetto/ubuntu-vnc-xfce-g3#22]
Thanks for this great work!
Just to let you know that this [Wiki page](https://github.com/accetto/ubuntu-vnc-xfce-g3/wiki/How-building-works) refers to the following files that are not in the repository anymore:
- Dockerfile.xfce.chromium
- Dockerfile.xfce.firefox

Probably related to pre g3 images.

**Comment by accetto** [comment]
Thanks a lot for the hint, I'll fix it. :)

**Comment by accetto** [comment]
@patlachance It's already fixed. Thanks a lot again.
