### ISSUE TITLE
Clipboard Sync

### ISSUE THREAD

**Issue by BlueCobbleStone** [accetto/ubuntu-vnc-xfce-g3#29]
Hi, thank you for this awsome image.

It would be nice to have clipboard synchronization between the host and the "guest" instead of having to use the novnc clipboard form.

**Comment by accetto** [comment]
Hello @BlueCobbleStone,

thank you for your feedback and the proposal. However, I'm afraid that I cannot do that for three reasons.

1. I don't know how I would implement it.
2. I'm afraid that it would be a security risk.
3. I would not be able to find the time for it.

I'm sorry.

Regards,
accetto
