### ISSUE TITLE
problem with youtube

### ISSUE THREAD

**Issue by carmineyiu** [accetto/ubuntu-vnc-xfce-g3#3]
Image and container are not modified. 
Open browser and enter youtube.com (youtube.com/?gl=HK)
--display 
Aw, Snap@ 
something went wrong while displaying this webpage
error code: SIGABRT

**Comment by carmineyiu** [comment]
Try youtube.com/?gl=US there is no issue
youtube.com/?gl=BR there is no issue
youtube.com/?gl=JP only font cannot display but no crash

**Comment by accetto** [comment]
Hello,

thank you for your feedback. However, I'm not able to reproduce the problem. Unfortunately you did not say, which image you've used. I've tested [accetto/ubuntu-vnc-xfce-chromium-g3:latest](https://hub.docker.com/r/accetto/ubuntu-vnc-xfce-chromium-g3) and [accetto/ubuntu-vnc-xfce-firefox-g3:latest](https://hub.docker.com/r/accetto/ubuntu-vnc-xfce-firefox-g3) and they both seem to work correctly out-of-the-box, at least from Europe. See the screenshots please.

Maybe it was something temporary and it already works also from your place?

One more remark: These headless containers are intdended to be used via VNC, which unfortunatelly does not support sound. So their usefulness for YouTube is somehow limited.

Regards,
accetto

***

This is the container with Chromium browser:

![youtube_chromium](https://user-images.githubusercontent.com/34798830/105740405-1a0c9300-5f31-11eb-90c8-23802b5b3a15.png)

This is the containet with Firefox browser:

![yutube_firefox](https://user-images.githubusercontent.com/34798830/105740437-25f85500-5f31-11eb-9a34-5bad1fcc6854.png)

**Comment by carmineyiu** [comment]
accetto/ubuntu-vnc-xfce-chromium-g3:latest  has issue, there is no issue with firefox image

**Comment by accetto** [comment]
Could you closer describe the behaviour please? What message you get exactly and when? Just after the start or later? What operating system and what VNC viewer do you use? Does it happen onyl with YouTube website or also with others? Do you have tried to install or configure something in the container or does it happen in the out-of-the-box state?

**Comment by carmineyiu** [comment]
docker run -d -P -e VNC_PW=password accetto/ubuntu-vnc-xfce-chromium-g3
then open Browser, enter youtube.com
click youtube.com
then go to blank screen with error coded. 

![Screen Sharing Picture 29 January 2021 at 1 45 27 AM HKT](https://user-images.githubusercontent.com/25974933/106177778-e43b0900-61d3-11eb-8eae-a4d721978723.png)

**Comment by accetto** [comment]
Thanks. I don't have the same environment, but I'll try to reproduce the problem. Could you test also the 1st and the 2nd generation images please?

2nd generation image: [accetto/xubuntu-vnc-novnc-chromium](https://hub.docker.com/r/accetto/xubuntu-vnc-novnc-chromium)
1st generation image: [accetto/ubuntu-vnc-xfce-chromium](https://hub.docker.com/r/accetto/ubuntu-vnc-xfce-chromium)

**Comment by carmineyiu** [comment]
Running is OMV Docker. 

docker run -d -P -e VNC_PW=amd2400g accetto/ubuntu-vnc-xfce-chromium
<img width="1249" alt="Screen Shot 2021-02-03 at 7 45 49 PM" src="https://user-images.githubusercontent.com/25974933/106743064-d7e20080-6658-11eb-9f14-d31331295687.png">
<img width="1106" alt="Screen Shot 2021-02-03 at 7 45 40 PM" src="https://user-images.githubusercontent.com/25974933/106743089-e203ff00-6658-11eb-83ed-c85e4280b8fd.png">

**Comment by carmineyiu** [comment]
Client tigerVNC Server OMV docker.
Docker run -d -P -e VNC_PW=amd2400g accetto/xubuntu-vnc-novnc-chromium
open www.youtube.com same as before. (default has CJK character) 
But if it open a youtube.com link  https://www.youtube.com/watch?v=rM2_2RyJoSQ&ab_channel=Handicrafts it is not crash, But some link still crash

**Comment by accetto** [comment]
Thanks. I'll try to reproduce it and to figure something out.

**Comment by accetto** [comment]
I've just released a new 2nd generation image [accetto/xubuntu-vnc-novnc-chrome](https://hub.docker.com/r/accetto/xubuntu-vnc-novnc-chrome). Maybe you can also check, if you'll get crashes.

**Comment by accetto** [comment]
I've tried all the scenarios you've described, but I still cannot reproduce the problem. It seems to be dependent on the locale or the geographical location, maybe. Sorry I couldn't help.
