### ISSUE TITLE
Overriding HEADLESS_USER_NAME doesn't seem to work

### ISSUE THREAD

**Issue by dtcooper** [accetto/ubuntu-vnc-xfce-g3#49]
Here's how to reproduce

```
docker run --rm -it -p 6901:6901 --env HEADLESS_USER_NAME=myuser accetto/ubuntu-vnc-xfce-opengl-g3:latest
```

Log in via noVNC with the password `headless`. Observe username is still `headless` and not `myuser`.

Cheers and thanks!

**Comment by accetto** [comment]
Hello @dtcooper,

thank you for you feedback.

Unfortunately, currently it's not possible to override the **user name** in the **run-time**, only in the build-time (s. [Overriding container user parameters](https://github.com/accetto/ubuntu-vnc-xfce-g3/blob/master/docker/xfce/README.md#overriding-container-user-parameters)).

I'm sorry for the confusion. I'm already working on a new documentation, which will not be so concise.

Regards,
accetto

**Comment by dtcooper** [comment]
Cheers thanks for the clarification and great family of containers! :)
