### ISSUE TITLE
Is it possiable to hide cursor in tigerVNC or change tigerVNC to X11VNC

### ISSUE THREAD

**Issue by dandelions** [accetto/ubuntu-vnc-xfce-g3#62]
I want to use novnc in --nocursor mode,but tigerVNC doesnot support it ,is it possiable to hide cursor in tigerVNC or change tigerVNC to X11VNC

**Comment by accetto** [comment]
Hello @dandelions ,

thank you for you feedback. However, I'm not sure, what actual effect should the option `--nocursor` have. Should it hide the mouse cursor or the cursor during text editing?

Maybe the `view-only mode`  would help? You can switch it on by setting the environment variable `VNC_VIEW_ONLY`. It's described on [this page](https://accetto.github.io/user-guide-g3/using-vnc/) in the [User Guide](https://accetto.github.io/user-guide-g3/).

Regards,
accetto

**Comment by accetto** [comment]
Closing the issue because I cannot really answer the question. Sorry.
