### ISSUE TITLE
Upgrade base image to Ubuntu 24.04

### ISSUE THREAD

**Issue by chenzilin** [accetto/ubuntu-vnc-xfce-g3#64]
When will you please upgrade the base image to Ubuntu 24.04?

**Comment by accetto** [comment]
Thank you for your feedback. I'm currently pretty busy with some other projects. However, I hope to be able to come to this one during this month.

**Comment by chenzilin** [comment]
So Great!

**Comment by accetto** [comment]
Done. The release **24.09** brings the images based on `Ubuntu 24.04 LTS`.
